In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

BZGBDA2021 = pd.read_excel(r"C:\Users\anton_zpf58tt\OneDrive\Documents\Glasgow\Year 4\ENG4110P Individual Project 4\Code\UK-Electricity-Pricing-Solutions\BZ_GB_20210101-20211231.xlsx", sheet_name='NordPool ASA GB')

#Date = pd.date_range(start="1/1/2021", periods=365, freq="D")

#|

#Date =  pd.date_range(start="1/1/2021", periods=365, freq="D")

BZGBDA2021data = pd.DataFrame({"BZN|GB": BZGBDA2021.iloc[0:365,2]})
BZGBDA2021data["Date"] = pd.date_range(start="1/1/2021", periods=365, freq="D")

NewOrder = ["Date", "BZN|GB"]

#BZGBDAdata["Date"] = pd.date_range(start="1/1/2021", periods=365, freq="D")
BZGBDA2021data = BZGBDA2021data.reindex(columns=NewOrder)
BZGBDA2021data

          Date      BZN|GB
0   2021-01-01   68.395938
1   2021-01-02   71.543775
2   2021-01-03   65.270347
3   2021-01-04   67.324756
4   2021-01-05   67.395083
..         ...         ...
360 2021-12-27  218.837199
361 2021-12-28  211.308121
362 2021-12-29  216.814897
363 2021-12-30  138.119945
364 2021-12-31  142.704115

[365 rows x 2 columns]

In [85]:
BZGBDA2022 = pd.read_csv(r"C:\Users\anton_zpf58tt\OneDrive\Documents\Glasgow\Year 4\ENG4110P Individual Project 4\Code\UK-Electricity-Pricing-Solutions\BZ_GB_20220101-20221231.csv")

print(BZGBDA2022)
#BZGBDA2021data = pd.DataFrame({"BZN|GB": BZGBDA2021.iloc[0:365,2]})
#BZGBDA2021data["Date"] = pd.date_range(start="1/1/2021", periods=365, freq="D")

#NewOrder = ["Date", "BZN|GB"]

#BZGBDAdata["Date"] = pd.date_range(start="1/1/2021", periods=365, freq="D")
#BZGBDA2021data = BZGBDA2021data.reindex(columns=NewOrder)
#BZGBDA2021data

BZGBDA2022data = pd.DataFrame({"BZN|GB": BZGBDA2022.iloc[0:,4] BZGBDA2022.iloc[0:,3]})
BZGBDA2022data

SyntaxError: invalid syntax (3513647728.py, line 13)